# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25a1472a4184463bb9877fe97e26a71241b486abbf624300ace1276d79934fb46afa96acc9ef9f5a638d1820e277f3dcfa7edb57ff4220c2919d0061464741f1

test:
  secret_key_base: a42ee46389a0f7657903601473e85b05561b98b1bbfeeb77ece7476d91281a28d03cfbe0b722a6dbf462dea140b07684eec5d7a6554998d3cfcc9b63aa5ca9d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
